# Generated by Django 5.0.7 on 2026-02-14 10:20

import ckeditor.fields
import django.db.models.deletion
import djangocms_text_ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSAccordionBaseCard',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(max_length=256)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CMSHTMLContent',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('content', djangocms_text_ckeditor.fields.HTMLField()),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CMSPlainText',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('text', models.TextField()),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CMSRichText',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('content', ckeditor.fields.RichTextField()),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CMSRichTextMemberCard',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('photo', models.ImageField(upload_to='headshots')),
                ('name', models.CharField(max_length=256)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CMSRichTextResourceCard',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=256)),
                ('body', ckeditor.fields.RichTextField()),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CMSSidebarImgDescBtnCard',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('photo', models.ImageField(upload_to='cms_images')),
                ('description', djangocms_text_ckeditor.fields.HTMLField()),
                ('button_text', models.CharField(max_length=256)),
                ('button_url', models.CharField(max_length=256)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CMSThemeBackgroundColorImageBtnCard',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('bg_color', models.CharField(choices=[('bg-primary', 'Primary Color'), ('bg-secondary', 'Secondary Color'), ('bg-success', 'Success Color'), ('bg-danger', 'Danger Color'), ('bg-warning', 'Warning Color'), ('bg-info', 'Info Color')], default='bg-primary', max_length=32)),
                ('overlay_image', models.ImageField(blank=True, upload_to='cms_images')),
                ('btn_href', models.URLField(blank=True, max_length=256)),
                ('btn_description', models.CharField(blank=True, max_length=64)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CMSThemeCTACard',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('description', models.TextField()),
                ('btn_color', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info')], default='primary', max_length=32)),
                ('btn_href', models.URLField(blank=True, max_length=256)),
                ('btn_name', models.CharField(blank=True, max_length=64)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CMSThemeIconBlockCard',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('svg_code', djangocms_text_ckeditor.fields.HTMLField()),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CMSThemeQuoteCard',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('brand_image', models.ImageField(blank=True, upload_to='cms_images')),
                ('quote', models.TextField()),
                ('person_image', models.ImageField(blank=True, upload_to='cms_images')),
                ('person_name', models.CharField(max_length=128)),
                ('person_designation', models.CharField(blank=True, max_length=128, null=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CMSThemeStatsCard',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('stats', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CMSThemeSupporterBoxBaseCard',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(max_length=256)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CMSThemeTwoImgsCard',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('photo_left', models.ImageField(upload_to='cms_images')),
                ('photo_right', models.ImageField(upload_to='cms_images')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='DivElement',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('class_names', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CMSAccordionItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('heading', models.CharField(max_length=256)),
                ('description', djangocms_text_ckeditor.fields.HTMLField()),
                ('accordion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lowbono_cms.cmsaccordionbasecard')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CMSThemeSupporterBoxItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('brand_name', models.ImageField(upload_to='cms_images')),
                ('brand_image', models.ImageField(upload_to='cms_images')),
                ('support_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lowbono_cms.cmsthemesupporterboxbasecard')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
