# Generated by Django 5.0.7 on 2026-02-14 10:20

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import localflavor.us.models
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryETATasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.CharField(max_length=256)),
                ('args', models.JSONField(null=True)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('SCHEDULED', 'Scheduled'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=64, null=True)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Celery ETA Task',
                'verbose_name_plural': 'Celery ETA Tasks',
            },
        ),
        migrations.CreateModel(
            name='EmailAPILogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.CharField(max_length=256)),
                ('api_logs', models.TextField(blank=True, null=True)),
                ('html_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email API Log',
                'verbose_name_plural': 'Email API Logs',
            },
        ),
        migrations.CreateModel(
            name='NewsArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('slug', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='news_images')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.CharField(default='LowBono Team', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PovertyLineRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_household_member_rate', models.IntegerField(default=1)),
                ('additional_household_member_rate', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SystemEmailTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('subject', models.CharField(max_length=512)),
                ('body', ckeditor.fields.RichTextField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'System Email Template',
                'verbose_name_plural': 'System Email Templates',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=150, verbose_name='username')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('firm_name', models.CharField(max_length=300)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.TextField()),
                ('photo', models.ImageField(upload_to='headshots')),
                ('bio', ckeditor.fields.RichTextField()),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BarAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('admission_date', models.DateField()),
                ('bar_number', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_admissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('subject', models.CharField(max_length=512)),
                ('body', ckeditor.fields.RichTextField()),
                ('recipient', models.CharField(choices=[(None, '[select recipient]'), ('PROFESSIONAL_EMAIL', 'Professional Email'), ('CLIENT_EMAIL', 'Client Email')], default='', max_length=128)),
                ('event_type', models.CharField(blank=True, choices=[(None, '[select event type]'), ('emailevententerstate', 'when a workflow enters state'), ('emaileventinactivefor', 'when a workflow has been inactive'), ('emaileventdeadline', 'when there is a deadline')], max_length=128, null=True)),
                ('active', models.BooleanField(default=True)),
                ('workflow_type', models.ForeignKey(limit_choices_to=models.Q(('app_label__icontains', 'lowbono'), ('model__icontains', 'workflow'), models.Q(('model__icontains', 'historical'), _negated=True), models.Q(('model__icontains', 'referralworkflowstate'), _negated=True)), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_type', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
            },
        ),
        migrations.CreateModel(
            name='EmailEventInactiveFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_state', models.CharField(default='', max_length=128)),
                ('days_inactive', models.IntegerField(default=0)),
                ('template', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lowbono_app.emailtemplates')),
            ],
            options={
                'verbose_name': 'EmailEvent InactiveFor',
                'verbose_name_plural': 'EmailEvents InactiveFor',
            },
        ),
        migrations.CreateModel(
            name='EmailEventEnterState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_state', models.CharField(default='', max_length=128)),
                ('days_after', models.IntegerField(default=0)),
                ('template', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lowbono_app.emailtemplates')),
            ],
            options={
                'verbose_name': 'EmailEvent Enter State',
                'verbose_name_plural': 'EmailEvents Enter State',
            },
        ),
        migrations.CreateModel(
            name='EmailEventDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_state', models.CharField(default='', max_length=128)),
                ('days', models.IntegerField(default=0)),
                ('before_or_after_deadline', models.CharField(choices=[('+', 'After Deadline'), ('-', 'Before Deadline')], default='-', max_length=4)),
                ('template', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lowbono_app.emailtemplates')),
            ],
            options={
                'verbose_name': 'EmailEvent Deadline',
                'verbose_name_plural': 'EmailEvents Deadline',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('ar-dz', 'Algerian Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('ckb', 'Central Kurdish (Sorani)'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('ig', 'Igbo'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('ky', 'Kyrgyz'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('ms', 'Malay'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('tg', 'Tajik'), ('th', 'Thai'), ('tk', 'Turkmen'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('ug', 'Uyghur'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], max_length=7)),
                ('bio', ckeditor.fields.RichTextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeArea',
            fields=[
                ('id', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('title_en', models.CharField(max_length=256, null=True)),
                ('title_es', models.CharField(max_length=256, null=True)),
                ('definition', models.TextField()),
                ('definition_en', models.TextField(null=True)),
                ('definition_es', models.TextField(null=True)),
                ('append_to_llm_definition', models.TextField(blank=True, null=True)),
                ('alternative_to_llm_definition', models.TextField(blank=True, null=True)),
                ('practicearea_type', models.ForeignKey(limit_choices_to=models.Q(('app_label__icontains', 'lowbono'), models.Q(('app_label__icontains', 'lawyer'), ('app_label__icontains', 'mediator'), _connector='OR'), models.Q(('model__icontains', 'referral'), _negated=True), models.Q(('model__icontains', 'practice'), _negated=True)), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practicearea_type', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'PracticeAreas',
            },
        ),
        migrations.CreateModel(
            name='LLMLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField(blank=True, null=True)),
                ('user_prompt', models.TextField(blank=True, null=True)),
                ('instruction_prompt', models.TextField(blank=True, null=True)),
                ('llm_result', models.TextField(blank=True, null=True)),
                ('audit_trail', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('practice_area_matched', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lowbono_app.practicearea')),
            ],
            options={
                'verbose_name': 'LLM Logs',
                'verbose_name_plural': 'LLM Logs',
            },
        ),
        migrations.CreateModel(
            name='PracticeAreaCategory',
            fields=[
                ('id', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('title_en', models.CharField(max_length=256, null=True)),
                ('title_es', models.CharField(max_length=256, null=True)),
                ('definition', models.TextField()),
                ('definition_en', models.TextField(null=True)),
                ('definition_es', models.TextField(null=True)),
                ('practicearea_category_type', models.ForeignKey(limit_choices_to=models.Q(('app_label__icontains', 'lowbono'), models.Q(('app_label__icontains', 'lawyer'), ('app_label__icontains', 'mediator'), _connector='OR'), models.Q(('model__icontains', 'referral'), _negated=True), models.Q(('model__icontains', 'practice'), _negated=True)), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practicearea_category_type', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Practice Area Categories',
            },
        ),
        migrations.AddField(
            model_name='practicearea',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='lowbono_app.practiceareacategory'),
        ),
        migrations.CreateModel(
            name='ProfileNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note by Admin on Professional',
                'verbose_name_plural': 'Notes by Admin on Professionals',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone')),
                ('address', models.TextField()),
                ('zipcode', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('monthly_income', models.IntegerField(blank=True, null=True)),
                ('household_size', models.IntegerField(blank=True, null=True)),
                ('income_status', models.CharField(blank=True, choices=[('low', 'Low Income'), ('moderate', 'Income Eligible'), ('high', 'Market Rate'), (None, 'Not Provided')], max_length=16, null=True)),
                ('in_dc', models.BooleanField(default=True)),
                ('allow_llm', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('ar-dz', 'Algerian Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('ckb', 'Central Kurdish (Sorani)'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('ig', 'Igbo'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('ky', 'Kyrgyz'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('ms', 'Malay'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('tg', 'Tajik'), ('th', 'Thai'), ('tk', 'Turkmen'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('ug', 'Uyghur'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], default='en', max_length=7, verbose_name='Your Language')),
                ('issue_description', models.TextField(blank=True, null=True, verbose_name='Briefly describe your legal issue')),
                ('follow_up_consent', models.BooleanField(default=False, verbose_name='May we follow up with you about your request (for example, with a request summary and survey)')),
                ('contact_preference', models.CharField(choices=[('0', 'Please contact me.'), ('1', 'I will contact the Lawyer/Mediator.')], max_length=1, verbose_name='If you request a consultation, do you give the lawyer permission to contact you?')),
                ('deadline_date', models.DateField(blank=True, default=None, null=True, verbose_name='when')),
                ('deadline_reason', models.CharField(blank=True, choices=[('Court hearing', 'Court hearing'), ('Filing deadline', 'Filing deadline'), ('Statute of limitations', 'Statute of limitations'), ('Response due', 'Response due'), ("Other/Don't know", "Other/Don't know")], max_length=32, null=True, verbose_name='what')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('practice_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lowbono_app.practicearea', verbose_name='Can you tell us more about your issue?')),
                ('professional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Who would you like to have a consultation with?')),
                ('referred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lowbono_app.referralsource', verbose_name='How did you find us?')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lowbono_app.referral')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note by Staff for Referral',
                'verbose_name_plural': 'Notes by Staff on Referrals',
            },
        ),
        migrations.CreateModel(
            name='ReferralNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=512, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('None', 'No Status'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('DELIVERED', 'Delivered')], default='None', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lowbono_app.referral')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lowbono_app.emailtemplates')),
            ],
            options={
                'verbose_name': 'Referral Notification',
                'verbose_name_plural': 'Referral Notifications',
            },
        ),
        migrations.CreateModel(
            name='SystemEmailEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='', max_length=128)),
                ('template', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lowbono_app.systememailtemplates')),
            ],
            options={
                'verbose_name': 'System EmailEvent',
                'verbose_name_plural': 'System EmailEvents',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token', models.CharField(max_length=43, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_day', models.DateField()),
                ('last_day', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
