# Generated by Django 5.0.7 on 2026-02-14 10:43
import json
from pathlib import Path

from django.db import migrations
from django.contrib.contenttypes.models import ContentType

DIR = Path(__file__).resolve().parents[1]
JSON_FILE_LAWYER = DIR / 'data/lawyer-practicearea-data.json' # this file is generated using a fixture script.
JSON_FILE_MEDIATOR = DIR / 'data/mediator-practicearea-data.json' # this file is generated using a fixture script.


def populate_practicearea_and_subtypes(apps, schema_editor):

    PracticeAreaCategory = apps.get_model('lowbono_app', 'PracticeAreaCategory')
    PracticeArea = apps.get_model('lowbono_app', 'PracticeArea')

    lawyer_model = apps.get_model("lowbono_lawyer", "lawyer")
    lwayer_ct = ContentType.objects.get_for_model(lawyer_model)

    mediator_model = apps.get_model("lowbono_mediator", "mediator")
    mediator_ct = ContentType.objects.get_for_model(mediator_model)

    pid = 1
    cid = 1
    with open(JSON_FILE_LAWYER) as f:
        for pa in json.load(f):
            parent = PracticeAreaCategory.objects.create(id=pid, title=pa["parent"]["title"], practicearea_category_type_id=lwayer_ct.id)
            pid += 1

            for ch in pa["children"]:
                PracticeArea.objects.create(id=cid, title=ch["title"], definition=ch["definition"], parent=parent, practicearea_type_id=lwayer_ct.id)
                cid += 1

    with open(JSON_FILE_MEDIATOR) as f:
        for pa in json.load(f):
            parent = PracticeAreaCategory.objects.create(id=str(pid), title=pa["parent"]["title"], title_en=pa["parent"]["title"], definition=pa["parent"]["definition"], definition_en=pa["parent"]["definition"], practicearea_category_type_id=mediator_ct.id)
            pid += 1

            for ch in pa["children"]:
                PracticeArea.objects.create(id=str(cid), title=ch["title"], definition=ch["definition"], title_en=ch["title"], definition_en=ch["definition"], parent=parent, practicearea_type_id=mediator_ct.id)
                cid += 1


class Migration(migrations.Migration):

    dependencies = [
        ('lowbono_app', '0001_initial'),
        ('lowbono_lawyer', '0001_initial'),
        ('lowbono_mediator', '0001_initial'),
        ('lowbono_cms', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_practicearea_and_subtypes),
    ]
