"""
Django settings for lowbono project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

HOST = 'http://192.168.239.128:8000' # 'https://lowbono.org' # kinda a hack - don't want to deal with extracting host from request for generating emails

AUTH_USER_MODEL = 'lowbono_app.User'

LOGIN_URL = '/professionals/login'

SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    'ckeditor',
    'phonenumber_field',
    'lowbono_app',
    'lowbono_lawyer',
    'lowbono_mediator',
    'lowbono_cms',
    'modeltranslation',
    'djangocms_text_ckeditor',
    'djangocms_admin_style', # must go before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    "crispy_forms",
    "crispy_bootstrap5",
    'django_bootstrap5',
    'nested_admin',
    'django.contrib.sites',
    'cms',
    'menus',
    'treebeard',
    'sekizai',
    'django_celery_beat',
    'django_celery_results',
    'reversion',
    'joeflow',
    'simple_history',
    'anymail',
    'django_htmx',
    'parler',
    'djangocms_alias',
    'easy_thumbnails',
    'filer',
    'djangocms_frontend',
    'djangocms_frontend.contrib.accordion',
    'djangocms_frontend.contrib.alert',
    'djangocms_frontend.contrib.badge',
    'djangocms_frontend.contrib.card',
    'djangocms_frontend.contrib.carousel',
    'djangocms_frontend.contrib.collapse',
    'djangocms_frontend.contrib.content',
    'djangocms_frontend.contrib.grid',
    'djangocms_frontend.contrib.icon',
    'djangocms_frontend.contrib.image',
    'djangocms_frontend.contrib.jumbotron',
    'djangocms_frontend.contrib.link',
    'djangocms_frontend.contrib.listgroup',
    'djangocms_frontend.contrib.media',
    'djangocms_frontend.contrib.tabs',
    'djangocms_frontend.contrib.utilities',

]

INSTALLED_PROFESSIONAL_APPS = ['lowbono_lawyer', 'lowbono_mediator']

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'lowbono.middleware.url_middleware.RequireLoginMiddleware',
    'lowbono.middleware.url_middleware.RequireStaffAccessMiddleware'
]

X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'lowbono.urls'

EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
EMAIL_FILE_PATH = BASE_DIR / 'emails'

EMAIL_ALIAS = 'LowBono Support <support@lowbono.org>'

MEDIA_ROOT = BASE_DIR / 'files'
MEDIA_URL = 'media/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cms.context_processors.cms_settings',
                'sekizai.context_processors.sekizai',
            ],
        },
    },
]

CMS_TEMPLATES = [
    ('lowbono_cms/default.html', 'Template: Default - No Content'),
    ('lowbono_cms/templates/header_2cols_left2x_right1x_static.html', 'Template: Header + 2 Columns - Left 2x, Right Static 1x'),
    ('lowbono_cms/templates/header_2cols_left2x_right1x.html', 'Template: Header + 2 Columns - Left 2x, Right 1x'),
    ('lowbono_cms/templates/header_center_content.html', 'Template: Header + Content Center Column'),

    ('lowbono_cms/templates/blue_header_2cols_left2x_right1x.html', 'Template: Blue Header + 2 Columns - Left 2x, Right 1x'),
    ('lowbono_cms/templates/blue_header_center_content.html', 'Template: Blue Header + Content Center Column'),

    ('lowbono_cms/home.html', 'Home page template'),
    ('lowbono_cms/about.html', 'About us page template'),
    ('lowbono_cms/mission-board.html', 'Mission and Board page template'),
    ('lowbono_cms/how-to-use.html', 'How To Use page template'),
    ('lowbono_cms/join-our-directory.html', 'Join Our Directory page template'),
    ('lowbono_cms/resources.html', 'Resources page template'),
    ('lowbono_cms/privacy.html', 'Privacy policy page template'),
    ('lowbono_cms/terms.html', 'Terms of Service page template'),
    ('lowbono_cms/donate.html', 'Donation page template'),
    ('lowbono_cms/imp-info-lowbono.html', 'Important Information about LowBono page template'),
]

CMS_CONFIRM_VERSION4 = True

WSGI_APPLICATION = 'lowbono.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', _('English')),
    ('es', _('Spanish')),
]

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = []
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

PHONENUMBER_DB_FORMAT = 'NATIONAL'
PHONENUMBER_DEFAULT_REGION = 'US'

# Celery Configs
CELERY_RESULT_BACKEND = 'django-db'

CELERY_IMPORTS = ['joeflow.runner.celery']

CELERY_TASK_ANNOTATIONS = {'*': {'default_retry_delay': 7200}}

JOEFLOW_CELERY_QUEUE_NAME = 'celery'
JOEFLOW_TASK_RUNNER = 'joeflow.runner.celery.task_runner'

CELERY_TASK_ROUTES = {
    'llm.*': {
        'queue': 'llm_queue',
    },
}

BETTER_UPTIME_CELERY_HEARTBEAT_URL = os.getenv('BETTER_UPTIME_CELERY_HEARTBEAT_URL')


LOGIN_REQUIRED_URLS = (r'/professionals/(.*)$', r'/referral_workflow/(.*)$',)
LOGIN_REQUIRED_URLS_EXCEPTIONS = (r'/professionals/signup/(.*)$', r'/professionals/login', r'/professionals/logout', r'/professionals/reset_password')

STAFF_LEVEL_ACCESS_REQUIRED_URLS = (r'/1referral_workflow/(.*)$',)

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList'],
            ['Link', 'Unlink'],
            ['Table'],
            ['RemoveFormat', 'Source']
        ],
        'width': '720',
    },
    'admin_toolbar': {
        'extraPlugins': ','.join(['image2', 'table']),
    },
}

HTML_SANITIZERS = {
    'default': {
        "tags": {
            "a", "strong", "em", "p", "ul", "ol", "li", "br", "hr",
            "table", "thead", "tbody", "tr", "th", "td",
        },
        "attributes": {"a": ("href", "name", "target", "title", "id", "rel")},
        "empty": {"hr", "a", "br"},
        "separate": {"a", "p", "li", "tr", "th", "td"},
        "whitespace": {"br"},
        "keep_typographic_whitespace": True,
    }
}

TEXT_ADDITIONAL_TAGS = ('iframe', 'script',)
TEXT_ADDITIONAL_ATTRIBUTES = ('frameborder', 'height', 'width', 'name', 'scrolling', 'seamless', 'src', 'style', 'paypalExpress')

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
OPENAI_MODEL = os.getenv('OPENAI_MODEL')
