# Generated by Django 5.0.7 on 2026-02-14 10:20

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lowbono_app', '0001_initial'),
        ('joeflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LawyerPracticeAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lowbono_lawyer.lawyer')),
                ('practicearea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_practice_areas', to='lowbono_app.practicearea')),
            ],
        ),
        migrations.AddField(
            model_name='lawyer',
            name='practice_areas',
            field=models.ManyToManyField(related_name='lawyer_practiceareas', through='lowbono_lawyer.LawyerPracticeAreas', to='lowbono_app.practicearea'),
        ),
        migrations.CreateModel(
            name='LawyerReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_referral', to='lowbono_app.referral')),
            ],
        ),
        migrations.CreateModel(
            name='LawyerLLMLogs',
            fields=[
                ('llmlogs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lowbono_app.llmlogs')),
                ('lawyer_referral', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lowbono_lawyer.lawyerreferral')),
            ],
            options={
                'verbose_name': 'Lawyer LLM Logs',
                'verbose_name_plural': 'Lawyer LLM Logs',
            },
            bases=('lowbono_app.llmlogs',),
        ),
        migrations.CreateModel(
            name='ReferralLawyerWorkflowState',
            fields=[
                ('workflow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='joeflow.workflow')),
                ('is_human_activity', models.BooleanField(default=True)),
                ('is_overdue', models.BooleanField(default=False)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_income_eligible', models.BooleanField(default=True)),
                ('ineligible_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='joeflow.task')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lowbono_app.referralnotifications')),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lowbono_app.referral')),
            ],
            options={
                'verbose_name': 'Referral Lawyer Workflow',
                'verbose_name_plural': 'Referral Lawyer Workflows',
            },
            bases=('joeflow.workflow', models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalReferralLawyerWorkflowState',
            fields=[
                ('workflow_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='joeflow.workflow')),
                ('id', models.BigIntegerField(blank=True, db_index=True, editable=False)),
                ('created', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('is_human_activity', models.BooleanField(default=True)),
                ('is_overdue', models.BooleanField(default=False)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_income_eligible', models.BooleanField(default=True)),
                ('ineligible_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('current_task', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='joeflow.task')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lowbono_app.referralnotifications')),
                ('referral', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lowbono_app.referral')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='lowbono_lawyer.referrallawyerworkflowstate')),
            ],
            options={
                'verbose_name': 'historical Referral Lawyer Workflow',
                'verbose_name_plural': 'historical Referral Lawyer Workflows',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
